worker_processes auto;
events { worker_connections 1024; }
http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    upstream api { server root-gateway:8220; }
    server {
        listen 80;
        root /usr/share/nginx/html;
        index index.html;
        location / { try_files $uri /index.html; }
        location /events { proxy_pass http://api/events; }
        location /services { proxy_pass http://api/services; }
        location /api/ { proxy_pass http://api/api/; }
        location /health { proxy_pass http://api/health; }
    }
}
